'use client';

// ===== MARKDOWN EXPORT =====
// Export translations to Markdown.

import React from 'react';

interface MarkdownExportOptions {
  code: string;
  language?: string;
  explanations: Array<{ line: number; text: string }>;
  title?: string;
}

/**
 * Generate Markdown content from translation.
 */
export function generateMarkdown(options: MarkdownExportOptions): string {
  const { code, language = 'typescript', explanations, title = 'Code Translation' } = options;
  const lines = code.split('\n');
  
  let md = `# ${title}\n\n`;
  md += `*Generated by Code Translator on ${new Date().toLocaleDateString()}*\n\n`;
  
  md += `## Source Code\n\n`;
  md += '```' + language + '\n' + code + '\n```\n\n';
  
  md += `## Line-by-Line Explanation\n\n`;
  
  for (const exp of explanations) {
    const codeLine = lines[exp.line - 1] || '';
    md += `### Line ${exp.line}\n\n`;
    md += '```' + language + '\n' + codeLine + '\n```\n\n';
    md += `${exp.text}\n\n`;
    md += '---\n\n';
  }
  
  return md;
}

/**
 * Download Markdown file.
 */
export function downloadMarkdown(options: MarkdownExportOptions, filename = 'translation.md'): void {
  const content = generateMarkdown(options);
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Copy Markdown to clipboard.
 */
export async function copyMarkdown(options: MarkdownExportOptions): Promise<void> {
  const content = generateMarkdown(options);
  await navigator.clipboard.writeText(content);
}

// Export button component
export function MarkdownExportButton({ 
  code, 
  language,
  explanations,
  title 
}: MarkdownExportOptions) {
  return (
    <button
      onClick={() => downloadMarkdown({ code, language, explanations, title })}
      className="flex items-center gap-2 px-3 py-2 bg-gray-700 hover:bg-gray-600 rounded text-gray-200 text-sm"
    >
      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
      </svg>
      Export Markdown
    </button>
  );
}

export default MarkdownExportButton;
