'use client';

// ===== PDF EXPORT =====
// Export translations to PDF.

import React from 'react';

interface ExportOptions {
  code: string;
  explanations: Array<{ line: number; text: string }>;
  title?: string;
  includeCode?: boolean;
  includeLineNumbers?: boolean;
}

/**
 * Generate printable HTML for PDF export.
 */
export function generatePrintableHTML(options: ExportOptions): string {
  const { code, explanations, title = 'Code Translation', includeCode = true, includeLineNumbers = true } = options;
  
  const lines = code.split('\n');
  
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; }
    h1 { color: #333; border-bottom: 2px solid #3b82f6; padding-bottom: 0.5rem; }
    .code-block { background: #1f2937; color: #e5e7eb; padding: 1rem; border-radius: 8px; font-family: monospace; white-space: pre-wrap; margin: 1rem 0; }
    .explanation { margin: 1rem 0; padding: 1rem; border-left: 3px solid #3b82f6; background: #f3f4f6; }
    .line-num { color: #6b7280; font-weight: bold; margin-right: 0.5rem; }
    .line-code { font-family: monospace; background: #e5e7eb; padding: 0.25rem 0.5rem; border-radius: 4px; }
    @media print { body { max-width: 100%; } }
  </style>
</head>
<body>
  <h1>${title}</h1>
  
  ${includeCode ? `
  <h2>Source Code</h2>
  <div class="code-block">${escapeHtml(code)}</div>
  ` : ''}
  
  <h2>Line-by-Line Explanation</h2>
  ${explanations.map(exp => `
    <div class="explanation">
      ${includeLineNumbers ? `<span class="line-num">Line ${exp.line}:</span>` : ''}
      <code class="line-code">${escapeHtml(lines[exp.line - 1] || '')}</code>
      <p>${escapeHtml(exp.text)}</p>
    </div>
  `).join('')}
  
  <footer style="margin-top: 2rem; text-align: center; color: #9ca3af; font-size: 0.875rem;">
    Generated by Code Translator • ${new Date().toLocaleDateString()}
  </footer>
</body>
</html>
  `.trim();
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Export to PDF using browser print.
 */
export function exportToPDF(options: ExportOptions): void {
  const html = generatePrintableHTML(options);
  const printWindow = window.open('', '_blank');
  
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.onload = () => {
      printWindow.print();
    };
  }
}

// Export button component
export function PDFExportButton({ 
  code, 
  explanations,
  title 
}: { 
  code: string; 
  explanations: Array<{ line: number; text: string }>;
  title?: string;
}) {
  return (
    <button
      onClick={() => exportToPDF({ code, explanations, title })}
      className="flex items-center gap-2 px-3 py-2 bg-gray-700 hover:bg-gray-600 rounded text-gray-200 text-sm"
    >
      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
      </svg>
      Export PDF
    </button>
  );
}

export default PDFExportButton;
